/*Aprendendo a alterar tabelas*/

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/*Adicionando primary key*/

ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

/*ADICIONANDO COLUNA SEM POSICAO, ULTIMA POSICAO*/
ALTER TABLE TABELA
ADD COLUNA4 VARCHAR(30);

/*ADICIONANDO UMA COLUNA EM UMA POSIÇÃO ESPECIFICA*/
ALTER TABLE TABELA
ADD COLUMN COLUNA_INTRUZA VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA2;

/*APRENDENDO A DROPAR COLUNA*/
ALTER TABLE TABELA
DROP COLUMN COLUNA_INTRUZA;

/*ALTERANDO UM CAMPO*/
ALTER TABLE TABELA MODIFY COLUNA_INTRUZA INT;

/*RENOMEANDO TABELA*/
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
	ID_TIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

--FOREIGN KEY 
ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/*VERIFICANDO CHAVES*/
SHOW CREATE TABLE TIME;
