/*Aprendendo sobre autorelacionamento*/

CREATE DATABASE ESCOLA_CURSOS;
USE ESCOLA_CURSOS;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    HORAS INT NOT NULL,
    VALOR FLOAT(10,2) NOT NULL,
    ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS(IDCURSO, NOME, HORAS, VALOR, ID_PREREQ) 
VALUES(NULL, 'CURSO LOGICA DE PROGRAMAÇÃO', 10, 120.00, NULL);

INSERT INTO CURSOS(IDCURSO, NOME, HORAS, VALOR, ID_PREREQ) 
VALUES(NULL, 'CURSO JAVA', 10, 120.00, 1);

INSERT INTO CURSOS(IDCURSO, NOME, HORAS, VALOR, ID_PREREQ) 
VALUES(NULL, 'CURSO BANCO DE DADOS', 10, 120.00, 1);

INSERT INTO CURSOS(IDCURSO, NOME, HORAS, VALOR, ID_PREREQ) 
VALUES(NULL, 'CURSO BI', 10, 120.00, 3);

SELECT 
    NOME, 
    HORAS, 
    VALOR, 
    (SELECT P.NOME FROM CURSOS P WHERE P.IDCURSO = C.ID_PREREQ) AS REQUISITO
FROM CURSOS C;

/*JEITO DO PROFESSOR*/

SELECT 
	C.NOME AS CURSO,
	C.VALOR AS VALOR,
	C.HORAS AS CARGA,
	IFNULL(P.NOME, '---') AS PREREQ
FROM CURSOS C LEFT JOIN CURSOS P 
ON P.IDCURSO = C.ID_PREREQ;
	
