/*COMO BANCOS SE COMUNICAM*/

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

STATUS

CREATE DATABASE BACKUP_LOJA;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

USE LOJA;

STATUS

INSERT INTO BACKUP_LOJA.BKP_PRODUTO VALUES(NULL,1000, 'TESTE', 0.0 )

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP_LOJA.BKP_PRODUTO(IDBKP, IDPRODUTO, NOME, VALOR) 
	VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);

END
$

DELIMITER ;

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO MODELAGEM', 120.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO JAVA', 150.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'NOTEBOOK', 3400.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO BI', 120.00);

DELETE FROM PRODUTO WHERE IDPRODUTO IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
 
DROP TRIGGER BACKUP_PRODUTO;
 
DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP_LOJA.BKP_PRODUTO(IDBKP, IDPRODUTO, NOME, VALOR) 
	VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);

END
$
DELIMITER ;

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO DE C#', 67.67);

SELECT * FROM BACKUP_LOJA.BKP_PRODUTO;

ALTER TABLE BACKUP_LOJA.BKP_PRODUTO
ADD EVENTO CHAR(1);

DELIMITER $

CREATE TRIGGER BACKUP_DELETE_PRODUTO
AFTER DELETE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP_LOJA.BKP_PRODUTO(IDBKP, IDPRODUTO, NOME, VALOR, EVENTO) 
	VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, 'D');

END
$

DROP TRIGGER BACKUP_PRODUTO;
 
DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP_LOJA.BKP_PRODUTO(IDBKP, IDPRODUTO, NOME, VALOR) 
	VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR, 'I');

END
$