/*DML de views*/

CREATE TABLE JOGARES(
	ID_JOGADORES INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	CLUBE VARCHAR(100),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES(ID_JOGADORES, NOME, CLUBE, ESTADO) VALUES(NULL, 'GABIGOL', 'SANTOS', 'SP');
INSERT INTO JOGADORES(ID_JOGADORES, NOME, CLUBE, ESTADO) VALUES(NULL, 'G.ARRASCAETA', 'FLAMENGO', 'SP');
INSERT INTO JOGADORES(ID_JOGADORES, NOME, CLUBE, ESTADO) VALUES(NULL, 'NEYMAR', 'SANTOS', 'SP');
INSERT INTO JOGADORES(ID_JOGADORES, NOME, CLUBE, ESTADO) VALUES(NULL, 'CALERI', 'SÃO PAULO', 'SP');


SELECT 	NOME, 
		CLUBE , 
		ESTADO
FROM JOGADORES;

 RENAME TABLE JOGARES TO JOGADORES;
 
 CREATE VIEW V_RELATORIO_JOGADORES AS 
	SELECT  ID_JOGADORES,
			NOME, 
			CLUBE , 
			ESTADO
	FROM JOGADORES;
	
INSERT INTO V_RELATORIO_JOGADORES(ID_JOGADORES, NOME, CLUBE, ESTADO) VALUES(NULL, 'BRUNO HENRIQUE', 'FLAMENGO', 'RJ');
 
SELECT * FROM JOGADORES;

DELETE FROM V_RELATORIO_JOGADORES
WHERE ID_JOGADORES = 2;