USE EMPRESA
GO


CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M', 'F'))
GO


/*1*1*/
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100, 10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL,
	CHECK (UF IN('RJ', 'SP', 'MG')),
	ID_ALUNO INT UNIQUE
)
GO

ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/*Aprendendo a mostrar as tabelas*/

SP_HELP ALUNO 
GO 

SP_COLUMNS ALUNO
GO

/*INSERT NAS TABLES*/

INSERT INTO ALUNO VALUES('ANDRE', 'M', '24/02/1985', 'ANDRE@GMAIL.COM')
INSERT INTO ALUNO VALUES('KAYO', 'M', '14/07/2013', 'KAYOZIN@GMAIL.COM')
INSERT INTO ALUNO VALUES('FERNANDA', 'F', '25/10/1990', 'FERNANDINHA@GMAIL.COM')
INSERT INTO ALUNO VALUES('ANDRESA', 'F', '14/11/1999', 'ANDRESA.PROF@GMAIL.COM')
GO

SELECT * FROM ALUNO
GO

SP_COLUMNS ENDERECO
GO

INSERT INTO ENDERECO VALUES('FLAMENGO', 'RJ', 1)
INSERT INTO ENDERECO VALUES('SÃO MATEUS', 'SP', 2)
INSERT INTO ENDERECO VALUES('MORUMBI', 'SP', 3)
INSERT INTO ENDERECO VALUES('BOTA FOGO', 'RJ', 4)
GO

SELECT * FROM ENDERECO
GO

/*CRIANDO TABELA DE TELEFONE 1*N*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3), 
	CHECK(TIPO IN('CEL', 'RES', 'COM')),
	NUMERO VARCHAR(20),
	IDALUNO INT
)
GO

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_ALUNO 
FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO)
GO

INSERT INTO TELEFONE VALUES('CEL', '(11)95682-0400', 1)
INSERT INTO TELEFONE VALUES('RES', '(11)92432-1234', 2)
INSERT INTO TELEFONE VALUES('COM', '(11)54354-5463', 3)
INSERT INTO TELEFONE VALUES('CEL', '(11)32432-0432', 4)
GO

SP_COLUMNS TELEFONE
GO

/*FAZENDO CONSULTAS COM JOIN*/

SELECT	A.NOME, 
		A.SEXO, 
		T.TIPO, 
		T.NUMERO , 
		E.UF
FROM ALUNO A
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
INNER JOIN TELEFONE T
ON A.IDALUNO = T.IDALUNO
GO

/*FUNÇÕES DE DATA*/

SELECT NOME, GETDATE() AS "DATA ATUAL"
FROM ALUNO
GO

SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE())/365 AS ANOS
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

SELECT DATEADD(DAY, 365, GETDATE())

/*CONVERSÃO DE DADOS*/

SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO

SELECT
	CAST(DAY(NASCIMENTO) AS VARCHAR(2)) + '/' + CAST(MONTH(NASCIMENTO) AS VARCHAR(2)) + '/' + CAST(YEAR(NASCIMENTO) AS VARCHAR(4))
FROM ALUNO
WHERE NOME = 'ANDRE'
GO
/*CHARINDEX*/

SELECT NOME, CHARINDEX('A', NOME)
FROM ALUNO
GO