/*OTIMIZANDO TRIGGERS*/

CREATE TABLE EMPREGADO(
	IDEMP INT PRIMARY KEY,
	NOME VARCHAR(30),
	SALARIO MONEY,
	IDGERENTE INT
)
GO

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(IDGERENTE) REFERENCES EMPREGADO(IDEMP)
GO

INSERT INTO EMPREGADO VALUES(1, 'CLARA', 5000.00, NULL)
INSERT INTO EMPREGADO VALUES(2, 'CELIA', 4000.00, 1)
INSERT INTO EMPREGADO VALUES(3, 'JOÃO', 4000.00, 1)
GO

DROP TABLE HIST_SALARIO
GO

CREATE TABLE HIST_SALARIO(
	IDEMPREGAOD INT,
	ANTIGOSAL MONEY,
	NOVOSAL MONEY,
	NOME VARCHAR(30),
	DATA DATETIME
)
GO


SP_RENAME 'HIST_SALARIO.IDEMPREGAOD', 'IDEMPREGADO', 'COLUMN'
GO

DROP TRIGGER TG_SALARIO
GO

CREATE TRIGGER TG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO
	(IDEMPREGADO, ANTIGOSAL, NOVOSAL, DATA)
	SELECT D.IDEMP, D.SALARIO, I.SALARIO, GETDATE()
	FROM DELETED D, INSERTED I
	WHERE D.IDEMP = I.IDEMP

END
GO

SELECT * FROM EMPREGADO
GO

UPDATE EMPREGADO SET SALARIO = SALARIO * 1.1
WHERE IDEMP = 1
GO

SELECT * FROM HIST_SALARIO
GO

DROP TRIGGER TG_SALARIO
GO

/*ATU TRIGGER*/
CREATE TRIGGER TG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO
	(IDEMPREGADO, ANTIGOSAL, NOVOSAL, NOME,  DATA)
	SELECT D.IDEMP, D.SALARIO, I.SALARIO, D.NOME,  GETDATE()
	FROM DELETED D, INSERTED I
	WHERE D.IDEMP = I.IDEMP

END
GO

SP_HELP HIST_SALARIO
GO

UPDATE EMPREGADO SET SALARIO = SALARIO * 1.1
WHERE IDEMP = 1
GO

SELECT * FROM HIST_SALARIO
GO