/* BLOCOS DE ATRIBUIÇAO DE VARIAVEIS */

DECLARE
	@CONTADOR INT
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR

END
GO


DECLARE 

	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20170207'
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'VALOR NUMERICO: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_DATA, 105)
END 
GO