/*IF E ELSE EM TSQL*/
DECLARE 
	@NUMERO INT = 6
BEGIN	
	IF @NUMERO = 6
		PRINT'O NÚMERO VALE ' + CAST(@NUMERO AS VARCHAR)
	ELSE 
		PRINT'O VALOR É FALSO'
END
GO

/* CASE */
DECLARE
	@CONTADOR INT 
BEGIN
	SELECT --O CASE REPRESENTA UMA COLUNA
	CASE
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMACOES",
	*
	FROM CARROS
END
GO

/*TRANSFORMANDO EM NOMEADO*/

CREATE PROC P_NUMERO_IGUAL_5 @V_NUMERO INT
AS
	BEGIN	
		IF @V_NUMERO = 5
			PRINT'O NUMERO VALE 5'
		ELSE 
			PRINT'NÃO, O NÚMERO VALE ' + CAST(@V_NUMERO AS VARCHAR)
	END
GO

P_NUMERO_IGUAL_5 5
f

/*APRENDENDO A UTILIZAR O WHILE*/
DECLARE 
	@I INT = 0
BEGIN
	WHILE (@I < 15)
	BEGIN 
		PRINT'O NUMERO VALE: ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1
	END

END 
GO