USE EMPRESA
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.TB_MARKETING
    (
    id int NOT NULL,
    nome nchar(30) NOT NULL
    )
GO
ALTER TABLE dbo.TB_MARKETING SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.TB_VENDAS
	(
	id int NOT NULL,
	nome nchar(100) NOT NULL
	)  ON GA_VENDAS
GO
ALTER TABLE dbo.TB_VENDAS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

CREATE TABLE empresa(
	id int,
	nome varchar(30)
);