/*Aprendendo a criar regras de negocio*/

SHOW DATABASES;

CREATE DATABASE ESCOLA_CURSOS;

CREATE TABLE CURSOS(
	ID_CURSOS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL		
);

INSERT INTO CURSOS(ID_CURSOS, NOME, HORAS, VALOR) VALUES(NULL, 'CURSO DE JAVA', 50, 110.00);
INSERT INTO CURSOS(ID_CURSOS, NOME, HORAS, VALOR) VALUES(NULL, 'CURSO DE BANCO DE DADOS', 50, 700.00);

DELIMITER #

CREATE PROCEDURE CAD_CURSOS(P_NOME VARCHAR(100),P_HORAS INT(3),P_VALOR FLOAT(10,2))
BEGIN 

	INSERT INTO CURSOS(ID_CURSOS, NOME, HORAS, VALOR) VALUES(NULL, P_NOME, P_HORAS, P_VALOR);

END
#

CALL CAD_CURSOS('Estrutura de dados', 70, 470.78)#
CALL CAD_CURSOS('Power BI', 20, 100.00)#
CALL CAD_CURSOS('JAVA', 100, 500.00)#
CALL CAD_CURSOS('UI/UX FRONT-END', 45, 250.78)#
CALL CAD_CURSOS('Arquitetura de redes', 120, 689.78)#

CREATE PROCEDURE VER_CURSOS()
BEGIN

	SELECT * FROM CURSOS;

END
#

CALL VER_CURSOS()#