USE EMPRESA
GO

CREATE TABLE CONTA(
	CONTA INT,
	VALOR INT,
	TIPO CHAR(1)
)
GO

SELECT * FROM CONTA
GO

BULK INSERT CONTA
FROM 'C:\Study_SQL\Fundamentos\CONTAS.txt'
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'CHAR',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

SELECT * FROM CONTA
GO

EXEC SP_RENAME 'CONTA.CONTA', 'IDCONTA', 'COLUMN';
GO

SP_HELP CONTA 
GO


SELECT 
    IDCONTA,
    SUM(CASE WHEN TIPO = 'D' THEN VALOR * 1 ELSE VALOR * -1 END) AS SALDO,
    CASE 
        WHEN SUM(CASE WHEN TIPO = 'C' THEN VALOR ELSE -VALOR END) >= 0 THEN 'CREDOR'
        ELSE 'DEVEDOR'
    END AS SITUACAO

FROM CONTA
GROUP BY IDCONTA;
GO


SELECT 
    IDCONTA,
    SUM(CASE WHEN TIPO = 'C' THEN VALOR ELSE -VALOR END) AS SALDO,
    CASE 
        WHEN SUM(CASE WHEN TIPO = 'C' THEN VALOR ELSE -VALOR END) >= 0 THEN 'CREDOR'
        ELSE 'DEVEDOR'
    END AS SITUACAO
FROM CONTA
GROUP BY IDCONTA;
GO

/*solução do professor*/

SELECT IDCONTA, VALOR, TIPO,
CHARINDEX('D', TIPO) AS DEBITO,
CHARINDEX('C', TIPO) AS CREDITO,
CHARINDEX('C', TIPO) * 2 - 1 AS MULTIPLICADOR
FROM CONTA
GO

SELECT IDCONTA, 
       SUM(VALOR * (CHARINDEX('C', TIPO) * 2 - 1)) AS SALDO
FROM CONTA
GROUP BY IDCONTA
GO