/*Aprendendo sobre constrains*/

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY(ID_JOGADOR)
	REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR(IDJOGADOR, NOME) VALUES(NULL, 'GUEREIRRO');
INSERT INTO TIME(IDTIME, NOMETIME, ID_JOGADOR) VALUES(NULL, 'FLAMENGO', 1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIME;

SHOW TABLES;

DROP TABLES CURSOS;
DROP TABLES PESSOA;
DROP TABLES VENDEDORES;

/*Sempre crie a tabela primeiro e depois nós colocamos as constraints*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	ID_CLIENTE INT
);

/*AGORA AS CONTRAINTS*/

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE 
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE 
PRIMARY KEY(IDTELEFONE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE CLIENTE;

SHOW DATABASES;

/*dicionario de dados*/

SHOW DATABASES;

USE information_schema;

DESC TABLE_CONSTRAINTS;

SELECT 	CONSTRAINT_SCHEMA AS 'BANCO',
		TABLE_NAME  AS 'TABELA',
		CONSTRAINT_NAME AS 'NOME_REGRA',
		CONSTRAINT_TYPE AS 'TIPO'
		FROM TABLE_CONSTRAINTS
		WHERE CONSTRAINT_SCHEMA = 'COMERCIO';
		
