/*cursores*/

CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	JAN INT, 
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'KEVIN', 9899, 6682, 8392);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'MARCIO', 3824, 2382, 6592);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'CLARA', 5349, 8572, 6953);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'ESTER', 7649, 1749, 0782);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'MAFRA', 3956, 3973, 4649);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'GLORIA', 3289, 3568, 6790);


INSERT INTO VENDEDORES(IDVENDEDOR, NOME, JAN, FEV, MAR) 
VALUES(NULL, 'RAFAEL', 8877, 9682, 2826);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA 
FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(30),
	JAN INT, 
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
	);
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	OPEN REG;
	
	REPEAT
		
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			
			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;
			
			INSERT INTO VEND_TOTAL(NOME, JAN, FEV, MAR, TOTAL, MEDIA) 
			VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
			
		END IF;
	
	UNTIL FIM END REPEAT;
	
	CLOSE REG;

END
$

DELIMITER ;

SELECT * FROM VENDEDORES;

CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;
