CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(40),
	PRECO INT,
	FRETE FLOAT(10,2)
);

DESC PRODUTO;

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO
MODIFY NOME_PRODUTO VARCHAR(40) NOT NULL;

/*Adicionando Colunas*/
ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

DESC PRODUTO;

/*Retirando colunas*/
ALTER TABLE PRODUTO
DROP COLUMN PESO;

/*Adicionando colunas em uma forma especifica*/
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;

/*Renomeando a tabela*/
RENAME TABLE PRODUTO TO TABELA_PRODUTO;