/*APRENDENDO SOBRE DELETE*/

SHOW DATABASES;

USE PROJETO;

SELECT * FROM CLIENTES;

SELECT * FROM CLIENTES 
WHERE NOME = 'CÉLIA' AND EMAIL IS NULL;

SELECT COUNT(*) FROM CLIENTES 
WHERE NOME = 'CÉLIA';

DELETE FROM CLIENTES 
WHERE NOME = 'CÉLIA' AND EMAIL IS NULL;

SELECT * FROM CLIENTES;