CREATE DATABASE COMERCIO;

SHOW DATABASES;

USE COMERCIO;

CREATE TABLE CLIENTES(
	IDCLIENTE int PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(150) UNIQUE,
	SEXO ENUM('M', 'F') NOT NULL,
	CPF VARCHAR(11) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO int PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	IDCLIENTE INT UNIQUE,
	FOREIGN KEY(IDCLIENTE) 
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE int PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM', 'RES', 'CEL') NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	IDCLIENTE INT,
	FOREIGN KEY(IDCLIENTE) 
	REFERENCES CLIENTES(IDCLIENTE)
);