/*Funções de agregação*/

CREATE TABLE VENDEDORES(
	ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(2) NOT NULL,
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'JOAO', 'M', 9867.00, 8786.00, 7453.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'MARIA', 'F', 2343.00, 3643.00, 6575.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'VITOR', 'M', 3242.00, 5475.00, 9766.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'ESTER', 'F', 7896.00, 6386.00, 1245.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'CLARA', 'F', 5323.00, 8323.00, 6789.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'ALFREDO', 'M', 7654.00, 2127.00, 7975.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'MARCOS', 'M', 5743.00, 4214.00, 7547.00);


INSERT INTO VENDEDORES(ID_VENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) 
VALUES(NULL, 'VITORIA', 'F', 3253.00, 6436.00, 4214.00);

/*Traz o valor maximo*/
SELECT MAX(FEVEREIRO) AS MAIOR
FROM VENDEDORES;

/*Traz o valor minimo*/
SELECT MIN(FEVEREIRO) AS MENOR
FROM VENDEDORES;

/*Traz o valor medio*/
SELECT AVG(FEVEREIRO) AS MEDIO
FROM VENDEDORES;

/*TRUNCATE*/
SELECT TRUNCATE(AVG(FEVEREIRO), 2) AS MEDIAN_FEV
FROM VENDEDORES;

/*somar as colunas*/
SELECT SUM(FEVEREIRO) AS TOTAL_FEV
FROM VENDEDORES;

/*AGRUPAR VENDAS POR SEXO*/
SELECT SEXO, SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDORES
GROUP BY SEXO;