/*Aprendendo a utilizar o JOIN*/

SELECT NOME, EMAIL, RUA, BAIRRO 
FROM CLIENTES
INNER JOIN ENDERECO
ON CLIENTES.IDCLIENTE = ENDERECO.IDCLIENTE;

SELECT NOME, SEXO, TIPO, NUMERO
FROM CLIENTES
INNER JOIN TELEFONE
ON CLIENTES.IDCLIENTE = TELEFONE.IDCLIENTE
WHERE SEXO = 'F';

/*Exercicio de JOIN*/

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO 
FROM CLIENTES C
INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.IDCLIENTE
INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.IDCLIENTE;