/*Aprendendo a utilizar o JOIN*/

SELECT NOME, EMAIL, RUA, BAIRRO 
FROM CLIENTES
INNER JOIN ENDERECO
ON CLIENTES.IDCLIENTE = ENDERECO.IDCLIENTE;

SELECT NOME, SEXO, TIPO, NUMERO
FROM CLIENTES
INNER JOIN TELEFONE
ON CLIENTES.IDCLIENTE = TELEFONE.IDCLIENTE
WHERE SEXO = 'F';