/*APRENDENDO A UTILIZAR OPERADORES LÓGICOS*/

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M' AND UF = 'SP';

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M' AND (UF = 'SP' OR  UF = 'MG');