SELECT * FROM FUNCIONARIOS
LIMIT 10;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, SUM(SALARIO) AS MONTANTE 
FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT SUM(SALARIO), AVG(SALARIO) FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, SUM(SALARIO) AS SALARIO_TOTAL, 
AVG(SALARIO) AS SALARIO_MEDIA 
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

SELECT DEPARTAMENTO, SUM(SALARIO) AS SALARIO_TOTAL, 
AVG(SALARIO) AS SALARIO_MEDIA 
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 ASC;

SELECT DEPARTAMENTO, SUM(SALARIO) AS SALARIO_TOTAL, 
AVG(SALARIO) AS SALARIO_MEDIA 
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 DESC;

