/*Refortação de strings*/

SELECT DISTINCT DEPARTAMENTO FROM FUNCIONARIOS;

/*Upper Case*/
SELECT DISTINCT UPPER(DEPARTAMENTO) FROM FUNCIONARIOS;

/*Lower Case*/
SELECT DISTINCT lower( DEPARTAMENTO) FROM FUNCIONARIOS;

/*CONCATENANDO STRINGS*/
SELECT CARGO || '-' || DEPARTAMENTO
FROM FUNCIONARIOS;

/*Contando funções*/
SELECT  LENGTH('   UNIDADOS    ')

/*ASSINTENTE*/
SELECT 	NOME,
		CARGO,
		CASE 
			WHEN CARGO LIKE '%Assistant%' THEN 1
			ELSE 0
		END AS ASSINTENTE
FROM FUNCIONARIOS  ;