SELECT * FROM FUNCIONARIOS;

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACAO;

SELECT SEXO, COUNT(SEXO) AS QUANTIDADE 
FROM FUNCIONARIOS GROUP BY SEXO;

SELECT DEPARTAMENTO, COUNT(DEPARTAMENTO) AS QUANTIDADE_DP 
FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT MAX(SALARIO) AS MAXIMO_SALARIO FROM FUNCIONARIOS;

SELECT MIN(SALARIO) AS MINIMO_SALARIO FROM FUNCIONARIOS;

SELECT MIN(SALARIO) AS MINIMO_SALARIO, MAX(SALARIO) AS MAXIMO_SALARIO 
FROM FUNCIONARIOS;

SELECT MIN(SALARIO) AS MINIMO_SALARIO, MAX(SALARIO) AS MAXIMO_SALARIO 
FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, MIN(SALARIO) AS MINIMO_SALARIO, MAX(SALARIO) AS MAXIMO_SALARIO 
FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT SEXO AS GENERO, MIN(SALARIO) AS MINIMO_SALARIO, MAX(SALARIO) AS MAXIMO_SALARIO 
FROM FUNCIONARIOS GROUP BY SEXO;

