/*FILTRO BASEADO EM PADRAO DE CARACTERES*/

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'B%' --USAR ASPAS SIMPLES
GROUP BY DEPARTAMENTO;

/*Aprendendo a utilizar having*/

SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'B%'
GROUP BY DEPARTAMENTO
HAVING SUM(SALARIO) > 4000000;