SELECT NOW() AS DATA_HORA;

SELECT 'KEVIN' AS 'DBA';

SELECT 'BANCO DE DADOS';

/*ALIAS DE COLUNAS*/

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTES;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTES;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTES;

/*APENAS PARA FINS ACADEMICOS*/

SELECT * FROM CLIENTES;