USE EMPRESA
GO


CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M', 'F'))
GO

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100, 10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL,
	CHECK (UF IN('RJ', 'SP', 'MG')),
	ID_ALUNO INT UNIQUE
)
GO

ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/*Aprendendo a mostrar as tabelas*/

SP_HELP ALUNO 
GO 

SP_COLUMNS ALUNO
GO

/*INSERT NAS TABLES*/

INSERT INTO ALUNO VALUES('ANDRE', 'M', '24/02/1985', 'ANDRE@GMAIL.COM')
INSERT INTO ALUNO VALUES('KAYO', 'M', '14/07/2013', 'KAYOZIN@GMAIL.COM')
INSERT INTO ALUNO VALUES('FERNANDA', 'F', '25/10/1990', 'FERNANDINHA@GMAIL.COM')
INSERT INTO ALUNO VALUES('ANDRESA', 'F', '14/11/1999', 'ANDRESA.PROF@GMAIL.COM')
GO