USE EMPRESA
GO

DROP TABLE PESSOA
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M', 'F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

DROP TABLE TELEFONE
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN('CEL', 'COM')),
	NUMERO VARCHAR(14) NOT NULL,
	IDPESSOA INT 
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA 
FOREIGN KEY(IDPESSOA) REFERENCES PESSOA(IDPESSOA)
GO

INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1976-10-10')
INSERT INTO PESSOA VALUES('JAIR', 'M', '1970-4-21')
INSERT INTO PESSOA VALUES('EDIVALDO', 'M', '1965-12-30')
GO

INSERT INTO TELEFONE VALUES('CEL', '(11)98763-9870', 1)
INSERT INTO TELEFONE VALUES('COM', '(11)92543-5432', 1)
INSERT INTO TELEFONE VALUES('COM', '(11)96543-2345', 2)
INSERT INTO TELEFONE VALUES('CEL', '(11)92134-6535', 2)
INSERT INTO TELEFONE VALUES('CEL', '(11)99695-2543', 3)
INSERT INTO TELEFONE VALUES('COM', '(11)94357-8764', 2)
INSERT INTO TELEFONE VALUES('COM', '(11)94564-9432', 1)

SELECT * FROM PESSOA
GO
SELECT * FROM TELEFONE
GO

/*Criando as proc ESTATICA E DINAMICA*/

/*ESTATICA: */
DROP PROC SOMA
GO

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
	PRINT('FEITA A PROC')

GO

EXEC SOMA 
GO

/*DINAMICA: */

CREATE PROC SOMA2 @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS SOMA

GO

EXEC SOMA2 92, 34
GO

/*PROCEDURES EM TABELAS: */

CREATE PROC TIPO_TELEFONE @TIPO CHAR(3)
AS
	SELECT P.NOME, T.NUMERO, T.TIPO
	FROM PESSOA P
	INNER JOIN TELEFONE T
		ON P.IDPESSOA = T.IDPESSOA
	WHERE TIPO = @TIPO
	GO

GO

EXEC TIPO_TELEFONE'CEL'
GO

EXEC TIPO_TELEFONE'COM'
GO

/*PROCEDURES COM PARAMETROS DE ENTRADA E DE SAÍDA*/

DROP PROC GETTIPO
GO

CREATE PROCEDURE GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE 
	WHERE TIPO = @TIPO
	GO

GO

DECLARE @SAIDA INT 
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT 
SELECT @SAIDA
GO