/*APRENDENDO SOBRE SUBQUERY*/

SELECT NOME, SEXO, MARCO AS MENOR_MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, SEXO, MARCO AS MENOR_MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME, SEXO, MARCO AS MEDIA_MARCO
FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);