/*TRIGGER DE AUDITORIA*/
DELIMITER ;

SHOW DATABASES;

DROP DATABASE AULA_TRIGGER;

DROP DATABASE BACKUP_LOJA;

DROP DATABASE LOJA;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR_ FLOAT(10,2)
);

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO MODELAGEM', 120.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO JAVA', 150.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'NOTEBOOK', 3400.00);

INSERT INTO LOJA.PRODUTO(IDPRODUTO, NOME, VALOR) 
VALUES(NULL, 'LIVRO BI', 120.00);

SELECT * FROM LOJA.PRODUTO;

ALTER TABLE LOJA.PRODUTO
RENAME COLUMN VALOR_ TO VALOR;

USE LOJA;

DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO(IDBACKUP, IDPRODUTO, NOME, VALOR_ORIGINAL, VALOR_ALTERADO, DATA, USUARIO, EVENTO)
	VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');

END
$

DELIMITER ;

UPDATE PRODUTO SET VALOR = 110.00
WHERE IDPRODUTO = 4;

SELECT * FROM PRODUTO;