/*APRENDENDO SOBRE TRIGGER*/

CREATE DATABASE AULA_TRIGGER;

USE AULA_TRIGGER;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	LOGIN VARCHAR(50),
	SENHA VARCHAR(20)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(50),
	LOGIN VARCHAR(50)
);

/*CRIANDO O TRIGGER*/

DELIMITER $

CREATE TRIGGER BKP_USUARIO 
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN

	INSERT INTO BKP_USUARIO (IDUSUARIO, NOME, LOGIN)
	VALUES (OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
 
END
$

DELIMITER ;

INSERT INTO USUARIO(NOME, LOGIN, SENHA) VALUES ('ANDRADE', 'ANDRADE2009', 'PENTALIBERTA');

SELECT * FROM USUARIO;

DELETE FROM USUARIO WHERE IDUSUARIO = 1;

SELECT * FROM  BKP_USUARIO;