/*Aprendendo sobre view*/
CREATE VIEW V_RELATORIO AS
	SELECT 	C.IDCLIENTE, 
			C.NOME, 
			C.SEXO,
			IFNULL(EMAIL, '******') AS EMAIL, 
			C.CPF, 
			E.RUA,
			E.BAIRRO,
			E.CIDADE,
			E.ESTADO,
			T.TIPO,
			T.NUMERO
	FROM CLIENTES C
	INNER JOIN ENDERECO E
		ON C.IDCLIENTE = E.IDCLIENTE
	INNER JOIN TELEFONE T
		ON C.IDCLIENTE = T.IDCLIENTE;