/*Aprendendo a utilizar filter*/
--sem:
SELECT COUNT(*) AS QUANTIDADE_TOTAL,
(SELECT COUNT(*) 
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS MASCULINO
FROM FUNCIONARIOS;

--com:
SELECT COUNT(*) AS QUANTIDADE_TOTAL,
COUNT(*) FILTER( WHERE SEXO = 'Masculino') as MASCULINO
FROM FUNCIONARIOS;

SELECT COUNT(*) AS QUANTIDADE_TOTAL,
COUNT(*) FILTER( WHERE SEXO = 'Feminino') as FEMININO,
COUNT(*) FILTER( WHERE DEPARTAMENTO = 'Books') as DEPARTAMENTO_Books
FROM FUNCIONARIOS;


