/*Trabalhando com dados de um CSV*/

CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(20),
	DIA INT,
	QUANTIDADE NUMERIC(10, 2)
);

COPY MAQUINAS
FROM 'C:\Study_SQL\Fundamentos\logMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS;

/*Média*/

SELECT MAQUINA, AVG(QUANTIDADE) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA;

/*USANDO ROUND*/
SELECT MAQUINA, ROUND(AVG(QUANTIDADE), 2) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA;

/*MODA*/
SELECT MAQUINA, QUANTIDADE, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY MAQUINA, QUANTIDADE
ORDER BY 3 DESC;

SELECT MAQUINA, QUANTIDADE, COUNT(*) FROM MAQUINAS 
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA , QUANTIDADE
ORDER BY 3 DESC
LIMIT 2;

/*moda do dataset inteiro*/

SELECT QUANTIDADE, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY QUANTIDADE
ORDER BY 2 DESC;

/*AMPLITUDE*/

SELECT 	MAQUINA,
		MAX(QUANTIDADE) AS MAXIMO,
		MIN(QUANTIDADE) AS MINIMO,
		MAX(QUANTIDADE) - MIN(QUANTIDADE) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY AMPLITUDE DESC;

/*MEDIA*/

SELECT 	MAQUINA,
		ROUND(AVG(QUANTIDADE), 2) AS MEDIA,
		MAX(QUANTIDADE) AS MAXIMO,
		MIN(QUANTIDADE) AS MINIMO,
		MAX(QUANTIDADE) - MIN(QUANTIDADE) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY AMPLITUDE DESC;

/*DESVIO PADRÃO E VARIANCIA*/

SELECT 	MAQUINA,
		ROUND(AVG(QUANTIDADE), 2) AS MEDIA,
		MAX(QUANTIDADE) AS MAXIMO,
		MIN(QUANTIDADE) AS MINIMO,
		MAX(QUANTIDADE) - MIN(QUANTIDADE) AS AMPLITUDE,
		ROUND(STDDEV_POP(QUANTIDADE), 2) AS DESV_PADRÃO_QTD,
		ROUND(VAR_POP(QUANTIDADE), 2) AS VARIANCIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY AMPLITUDE DESC;

/* MEDIANA - FUNÇÃO E AGREGADOR */


CREATE OR REPLACE FUNCTION _FINAL_MEDIAN(NUMERIC[])
RETURNS NUMERIC AS 
$$
    SELECT AVG(VAL)
    FROM (
        SELECT VAL
        FROM UNNEST($1) AS VAL
        ORDER BY 1
        LIMIT 2 - MOD(ARRAY_UPPER($1, 1), 2)
        OFFSET CEIL(ARRAY_UPPER($1, 1) / 2.0) - 1
    ) AS SUB;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE MEDIAN(NUMERIC) (
    SFUNC = ARRAY_APPEND,
    STYPE = NUMERIC[],
    FINALFUNC = _FINAL_MEDIAN,
    INITCOND = '{}'
);

SELECT * FROM MAQUINAS;

SELECT MEDIAN(QUANTIDADE) AS MEDIANA FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03';

/*QUERY COMPLETA DE ANALISE DE DADOS */

SELECT 	MAQUINA,
		SUM(QUANTIDADE) AS TOTAL,
		ROUND(AVG(QUANTIDADE), 2) AS MEDIA,
		MAX(QUANTIDADE) AS MAXIMO,
		MIN(QUANTIDADE) AS MINIMO,
		MAX(QUANTIDADE) - MIN(QUANTIDADE) AS AMPLITUDE,
		ROUND(VAR_POP(QUANTIDADE), 2) AS VARIANCIA_QTD,
		ROUND(STDDEV_POP(QUANTIDADE), 2) AS DESV_PADRÃO_QTD,
		MEDIAN(QUANTIDADE) AS MEDIANA,
		(STDDEV_POP(QUANTIDADE) / AVG(QUANTIDADE)) * 100 AS COEF_VARIAÇÃO 
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY AMPLITUDE DESC;

/*MODA*/

SELECT MAQUINA, MODE() WITHIN GROUP(ORDER BY QUANTIDADE) AS MODA 
FROM MAQUINAS
GROUP BY MAQUINA;

SELECT 	MAQUINA,
		SUM(QUANTIDADE) AS TOTAL,
		ROUND(AVG(QUANTIDADE), 2) AS MEDIA,
		MAX(QUANTIDADE) AS MAXIMO,
		MIN(QUANTIDADE) AS MINIMO,
		MAX(QUANTIDADE) - MIN(QUANTIDADE) AS AMPLITUDE,
		ROUND(VAR_POP(QUANTIDADE), 2) AS VARIANCIA_QTD,
		ROUND(STDDEV_POP(QUANTIDADE), 2) AS DESV_PADRÃO_QTD,
		MEDIAN(QUANTIDADE) AS MEDIANA,
		(STDDEV_POP(QUANTIDADE) / AVG(QUANTIDADE)) * 100 AS COEF_VARIAÇÃO,
		MODE() WITHIN GROUP(ORDER BY QUANTIDADE) AS MODA 
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY AMPLITUDE DESC;
