/*Fazendo a trigger para deixar a atualização, automatica na tabela de relatório.*/

CREATE OR REPLACE FUNCTION ATUALIZA_REL() -- ESSA É A FUNÇÃO
RETURNS TRIGGER AS $$
BEGIN

	INSERT INTO RELATORIO_LOCADORA
	SELECT L.IDLOCACAO, F.NOME AS FILME, G.NOME AS GENERO, 
	L.DATA AS DATA, L.DIAS AS DIAS, L.MIDIA AS MIDIA
	FROM GENERO G
	INNER JOIN FILME F
	ON G.IDGENERO = F.ID_GENERO
	INNER JOIN LOCACAO L
	ON L.ID_FILME = F.IDFILME
	WHERE IDLOCACAO NOT IN (SELECT IDLOCACAO FROM RELATORIO_LOCADORA);

	COPY RELATORIO_LOCADORA TO
	'C:\Study_SQL\Fundamentos\RELATORIO_LOCADORA'
	DELIMITER ';'
	CSV HEADER;
RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;

--CRIANDO A TRIGGER

DROP TRIGGER TG_RELATORIO ON LOCACAO;

CREATE TRIGGER TG_RELATORIO
AFTER INSERT ON LOCACAO
FOR EACH ROW 
	EXECUTE PROCEDURE ATUALIZA_REL();

INSERT INTO LOCACAO VALUES(NEXTVAL('SEQ_LOCACAO'), NOW(), 500,1,200);
INSERT INTO LOCACAO VALUES(NEXTVAL('SEQ_LOCACAO'), NOW(), 800,1,500);

SELECT * FROM RELATORIO_LOCADORA;