-- CRIANDO A FUNÇÃO DE DELETE

DROP FUNCTION DELETE_LOCACAO();

CREATE OR REPLACE FUNCTION DELETE_LOCACAO()
RETURNS TRIGGER AS $$
BEGIN
	
	DELETE FROM RELATORIO_LOCADORA
	WHERE IDLOCACAO = OLD.IDLOCACAO;

	COPY RELATORIO_LOCADORA TO 
	'C:/Study_SQL/Fundamentos/RELATORIO_LOCADORA.csv'
	DELIMITER ';'
	CSV HEADER;
	
	RETURN OLD;
END;
$$
LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS DELETE_REG ON LOCACAO;

CREATE TRIGGER DELETE_REG
	BEFORE DELETE ON LOCACAO
	FOR EACH ROW
	EXECUTE PROCEDURE DELETE_LOCACAO();

SELECT * FROM RELATORIO_LOCADORA;
SELECT * FROM LOCACAO;

DELETE FROM LOCACAO
WHERE IDLOCACAO = 1;