/*Exercicio de DDL*/

ALTER TABLE CLIENTES
MODIFY SEXO ENUM('M','F') NOT NULL AFTER NOME;

TRUNCATE TABLE CLIENTES;

TRUNCATE TABLE ENDERECO;

TRUNCATE TABLE TELEFONE;

DELETE FROM CLIENTES;

/*DANDO INSERT NA TABLE CLIENTES*/
INSERT INTO CLIENTES VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTES VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTES VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTES VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTES VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTES VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTES VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTES VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTES VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTES VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTES VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTES VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');
INSERT INTO CLIENTES VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');

/*DANDO INSERT NA TABLE TELEFONE*/
INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',21);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',21);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',26);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',26);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',26);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',25);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',24);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',23);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',23);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',28);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',27);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);

/*DANDO INSERT NA TABLE ENDERECO*/
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',21);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ', 26);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ', 28);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',27);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',23);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',25);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',22);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP', 30);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',29);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',24);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

/*RELATORIO GERAL DE TODOS OS CLIENTES*/
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, 
C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTES C
INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.IDCLIENTE
INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.IDCLIENTE;
	
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       | RUA                | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO   |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+
|        21 | GIOVANA | F    | NULL              | 0876655   | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 68976565 |
|        21 | GIOVANA | F    | NULL              | 0876655   | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 99656675 |
|        26 | ANTONIO | M    | ANTONIO@IG.COM    | 12436767  | RUA MAIA LACERDA   | ESTACIO    | RIO DE JANEIRO | RJ     | CEL  | 33567765 |
|        26 | ANTONIO | M    | ANTONIO@IG.COM    | 12436767  | RUA MAIA LACERDA   | ESTACIO    | RIO DE JANEIRO | RJ     | CEL  | 88668786 |
|        26 | ANTONIO | M    | ANTONIO@IG.COM    | 12436767  | RUA MAIA LACERDA   | ESTACIO    | RIO DE JANEIRO | RJ     | COM  | 55689654 |
|        25 | EDUARDO | M    | NULL              | 54376457  | RUA CASTRO ALVES   | LEBLON     | RIO DE JANEIRO | RJ     | COM  | 88687979 |
|        24 | LORENA  | F    | NULL              | 774557887 | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | COM  | 88965676 |
|        23 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | CEL  | 89966809 |
|        23 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | COM  | 88679978 |
|        28 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 99655768 |
|        27 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565   | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | RES  | 89955665 |
|        19 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765   | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786 |
|        19 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765   | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554 |
|        20 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567   | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785 |
|        20 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567   | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578 |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+------+----------+


/*RELATORIO DOS HOMENS*/
SELECT * FROM CLIENTES
WHERE SEXO = 'M';

+-----------+---------+------+-------------------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       |
+-----------+---------+------+-------------------+-----------+
|        19 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765   |
|        20 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567   |
|        22 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778 |
|        23 | DANIELE | M    | DANIELE@GMAIL.COM | 43536789  |
|        24 | LORENA  | M    | NULL              | 774557887 |
|        25 | EDUARDO | M    | NULL              | 54376457  |
|        27 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565   |
|        28 | ELAINE  | M    | ELAINE@GLOBO.COM  | 32567763  |
|        31 | CARMEM  | M    | CARMEM@IG.COM     | 787832213 |
+-----------+---------+------+-------------------+-----------+

UPDATE CLIENTES
SET SEXO = 'F'
WHERE NOME IN ('KARLA', 'DANIELE', 'LORENA', 'ELAINE', 'CARMEM');

+-----------+---------+------+-----------------+----------+
| IDCLIENTE | NOME    | SEXO | EMAIL           | CPF      |
+-----------+---------+------+-----------------+----------+
|        19 | FLAVIO  | M    | FLAVIO@IG.COM   | 4657765  |
|        20 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567  |
|        25 | EDUARDO | M    | NULL            | 54376457 |
|        27 | ANTONIO | M    | ANTONIO@UOL.COM | 3423565  |
+-----------+---------+------+-----------------+----------+

/*RELATORIO DAS MULHERES*/
SELECT * FROM CLIENTES
WHERE SEXO = 'F';

+-----------+---------+------+-------------------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       |
+-----------+---------+------+-------------------+-----------+
|        21 | GIOVANA | F    | NULL              | 0876655   |
|        22 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 |
|        23 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  |
|        24 | LORENA  | F    | NULL              | 774557887 |
|        26 | ANTONIO | F    | ANTONIO@IG.COM    | 12436767  |
|        28 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  |
|        29 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  |
|        30 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256  |
|        31 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 |
+-----------+---------+------+-------------------+-----------+

UPDATE CLIENTES 
SET SEXO = 'M'
WHERE NOME = 'ANTONIO';
+-----------+---------+------+-------------------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       |
+-----------+---------+------+-------------------+-----------+
|        21 | GIOVANA | F    | NULL              | 0876655   |
|        22 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 |
|        23 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  |
|        24 | LORENA  | F    | NULL              | 774557887 |
|        28 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  |
|        29 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  |
|        30 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256  |
|        31 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 |

/*QUANTIDADE DE HOMENS E MULHERES*/
SELECT COUNT(*), SEXO FROM CLIENTES
GROUP BY SEXO;

+----------+------+
| COUNT(*) | SEXO |
+----------+------+
|        5 | M    |
|        8 | F    |
+----------+------+

/*IDS E EMAILS DE MULHERES QUE MOREM NO CENTRO DO RJ E NÃO TENHAM CELULAR */
SELECT C.IDCLIENTE, C.EMAIL 
FROM CLIENTES C
INNER JOIN ENDERECO E 
    ON C.IDCLIENTE = E.IDCLIENTE
LEFT JOIN TELEFONE T 
    ON C.IDCLIENTE = T.IDCLIENTE
WHERE C.SEXO = 'F' 
  AND E.BAIRRO = 'CENTRO' 
  AND T.NUMERO IS NULL;
  
+-----------+-----------------+
| IDCLIENTE | EMAIL           |
+-----------+-----------------+
|        22 | KARLA@GMAIL.COM |
+-----------+-----------------+