CREATE DATABASE IF NOT EXISTS PROJETO_OFICINA;

USE PROJETO_OFICINA;

/* CRIAÇÃO DAS TABELAS */

CREATE TABLE CLIENTES(
	IDCLIENTE INT,
	NOME_CLIENTE VARCHAR(100) NOT NULL
);

CREATE TABLE TELEFONE_CLIENTES(
	IDTELEFONE INT,
	NUMERO_TELEFONE VARCHAR(20) NOT NULL UNIQUE,
	ID_CLIENTE INT NOT NULL
);

CREATE TABLE CARROS_CLIENTES(
	IDCARRO INT,
	MARCA VARCHAR(30) NOT NULL,
	PLACA_CARRO VARCHAR(8) NOT NULL UNIQUE,
	ID_CLIENTE INT NOT NULL
);

CREATE TABLE COR_TINTA_CARROS(
	IDCOR INT,
	COR_NOME VARCHAR(30),
	ID_CARRO INT NULL
);

/*CONSTRAINTS DE PRIMARY KEY */

ALTER TABLE CLIENTES ADD CONSTRAINT
PK_CLIENTES PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE_CLIENTES ADD CONSTRAINT
PK_TELEFONE_CLIENTES PRIMARY KEY(IDTELEFONE);

ALTER TABLE CARROS_CLIENTES ADD CONSTRAINT
PK_CARROS_CLIENTES PRIMARY KEY(IDCARRO);

ALTER TABLE COR_TINTA_CARROS ADD CONSTRAINT
PK_TINTA_CARROS PRIMARY KEY(IDCOR);

/*ATRIBUIÇÃO DE AUTO_INCREMENT (Antes de criar as FKs) */

ALTER TABLE CLIENTES 
MODIFY COLUMN IDCLIENTE INT AUTO_INCREMENT;

ALTER TABLE TELEFONE_CLIENTES
MODIFY COLUMN IDTELEFONE INT AUTO_INCREMENT;

ALTER TABLE CARROS_CLIENTES
MODIFY COLUMN IDCARRO INT AUTO_INCREMENT;

ALTER TABLE COR_TINTA_CARROS
MODIFY COLUMN IDCOR INT AUTO_INCREMENT;

/*CONSTRAINTS DE FOREIGN KEY */

ALTER TABLE TELEFONE_CLIENTES ADD CONSTRAINT
FK_TELEFONE_CLIENTES FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTES(IDCLIENTE);

ALTER TABLE CARROS_CLIENTES ADD CONSTRAINT
FK_CARROS_CLIENTES FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTES(IDCLIENTE);

ALTER TABLE COR_TINTA_CARROS ADD CONSTRAINT
FK_COR_TINTA_CARROS FOREIGN KEY(ID_CARRO)
REFERENCES CARROS_CLIENTES(IDCARRO);

/*INSERÇÃO DOS DADOS */

INSERT INTO CLIENTES(NOME_CLIENTE)
VALUES('JAIR MESSIAS');

INSERT INTO TELEFONE_CLIENTES(NUMERO_TELEFONE, ID_CLIENTE)
VALUES('11 98765-3456', 1);

INSERT INTO CARROS_CLIENTES(MARCA, PLACA_CARRO, ID_CLIENTE)
VALUES('FORD', 'FRD-4486', 1);

INSERT INTO COR_TINTA_CARROS(COR_NOME, ID_CARRO)
VALUES('AMARELO', 1);


SELECT C.IDCLIENTE, C.NOME_CLIENTE,
T.NUMERO_TELEFONE,CC.MARCA,CC.PLACA_CARRO,
CTC.COR_NOME
FROM CLIENTES C
INNER JOIN TELEFONE_CLIENTES T
	ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN CARROS_CLIENTES CC
	ON C.IDCLIENTE = CC.ID_CLIENTE
INNER JOIN COR_TINTA_CARROS CTC
	ON CC.IDCARRO = CTC.ID_CARRO;